# Generated by Django 5.1 on 2024-08-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('years_of_exp', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('current_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], default='Applied', max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='candidates__name_ed6dc8_idx'), models.Index(fields=['phone_number'], name='candidates__phone_n_77992f_idx'), models.Index(fields=['email'], name='candidates__email_188e48_idx')],
            },
        ),
    ]
